name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go: [ "1.18", "1.19" ]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Golang ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: lint
        run: |
          cd $GITHUB_WORKSPACE
          go vet ./...
      - name: tests
        run: go test ./... -timeout 30s -race

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Index module
        run: GOPROXY=proxy.golang.org go list -m github.com/sopherapps/go-scdb@$GITHUB_REF_NAME
