name: CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: [ "1.18", "1.19" ]
    runs-on: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Golang ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: lint
        run: |
          cd $GITHUB_WORKSPACE/projects/dataframe
          go vet ./...
      - name: tests
        run: go test ./... -timeout 30s -race
